easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:  /app
api:
    type: rest
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix: /api

api_login_check:
    path: /api/login_check