app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:  /app
api:
    type: rest
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix: /api

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

api_login_check:
    path: /api/login_check